### ISSUE TITLE
rhvoice build error

### ISSUE THREAD

**Issue by lavrenkov-sketch** [Aculeasis/rhvoice-proxy#2]
After install, when try start
python3 rhvoice-rest.py

Warning! Preprocessing disable: No module named 'rhvoice_tools'
Warning! Unsupported library version (API: ('0.7.2', '1.0.0'); LIB: 1.2.0)
Traceback (most recent call last):
  File "rhvoice-rest.py", line 114, in <module>
    tts = TTS()
  File "/usr/local/lib/python3.7/dist-packages/rhvoice_wrapper/rhvoice_wrapper.py", line 489, in __init__
    self._voices = test.voices
  File "/usr/local/lib/python3.7/dist-packages/rhvoice_wrapper/rhvoice_proxy.py", line 303, in voices
    return get_voices(self._lib, self._engine)
  File "/usr/local/lib/python3.7/dist-packages/rhvoice_wrapper/rhvoice_proxy.py", line 269, in get_voices
    country='NaN' if old else vi.country.decode()
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by lavrenkov-sketch** [comment]
I have version 0.5.1 but when install 0.5.2 all ok!
with this tip:
0.5.2 - python3 -m pip install -U rhvoice-wrapper.
